/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jimschenchen
 */
public class MainWindows extends javax.swing.JFrame {

    private Database db;

    /**
     * Creates new form MainWindows
     */
    public MainWindows() {
        db = new Database();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jDFileChoose = new javax.swing.JDialog();
        jFileChooser = new javax.swing.JFileChooser();
        jDFile = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jBCalculate = new javax.swing.JButton();
        jBSave = new javax.swing.JButton();
        jTMessage = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jText = new javax.swing.JTextField();
        jBAc = new javax.swing.JButton();
        jBDel = new javax.swing.JButton();
        jBPercentage = new javax.swing.JButton();
        jBDivide = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jBTimes = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jBminus = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jBPlus = new javax.swing.JButton();
        jB0 = new javax.swing.JButton();
        jBDot = new javax.swing.JButton();
        jBEqual = new javax.swing.JButton();
        jBHappy = new javax.swing.JButton();
        jBCry = new javax.swing.JButton();
        jBSad = new javax.swing.JButton();
        jBHeart = new javax.swing.JButton();
        jBSr3 = new javax.swing.JButton();
        jBSr2 = new javax.swing.JButton();
        jBPowerX = new javax.swing.JButton();
        jBClosingBracket = new javax.swing.JButton();
        jBOpeningBracket = new javax.swing.JButton();
        jBSquare = new javax.swing.JButton();
        jBFile = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTHistory = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jDFileChoose.setAlwaysOnTop(true);
        jDFileChoose.setSize(new java.awt.Dimension(600, 400));
        jDFileChoose.getContentPane().setLayout(new java.awt.BorderLayout(300, 400));

        jFileChooser.setFileFilter(null);
        jFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserActionPerformed(evt);
            }
        });
        jDFileChoose.getContentPane().add(jFileChooser, java.awt.BorderLayout.LINE_END);

        jDFile.setResizable(false);
        jDFile.setSize(new java.awt.Dimension(800, 600));
        jDFile.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 350));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Please edit and save first\nThen the calculator will help to calculate from the orignal firl\nSave the result after you click calculate");
        jTextArea1.setPreferredSize(new java.awt.Dimension(100, 40));
        jScrollPane1.setViewportView(jTextArea1);

        jDFile.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 770, 500));

        jBCalculate.setText("Calculate");
        jBCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalculateActionPerformed(evt);
            }
        });
        jDFile.getContentPane().add(jBCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jBSave.setText("Save");
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });
        jDFile.getContentPane().add(jBSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, -1));

        jTMessage.setText("Waiting...");
        jDFile.getContentPane().add(jTMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 510, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(905, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jText.setBackground(new java.awt.Color(51, 51, 51));
        jText.setFont(new java.awt.Font("Source Code Pro Black", 0, 24)); // NOI18N
        jText.setForeground(new java.awt.Color(255, 204, 204));
        jText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jText.setText("0");
        jText.setBorder(null);
        jPanel1.add(jText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 880, 130));

        jBAc.setText("AC");
        jBAc.setFocusPainted(false);
        jBAc.setIconTextGap(0);
        jBAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAcActionPerformed(evt);
            }
        });
        jPanel1.add(jBAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 100, 80));

        jBDel.setText("Del");
        jBDel.setFocusPainted(false);
        jBDel.setIconTextGap(0);
        jBDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDelActionPerformed(evt);
            }
        });
        jPanel1.add(jBDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 100, 80));

        jBPercentage.setText("%");
        jBPercentage.setFocusPainted(false);
        jBPercentage.setIconTextGap(0);
        jBPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPercentageActionPerformed(evt);
            }
        });
        jPanel1.add(jBPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 100, 80));

        jBDivide.setText("÷");
        jBDivide.setFocusPainted(false);
        jBDivide.setIconTextGap(0);
        jBDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDivideActionPerformed(evt);
            }
        });
        jPanel1.add(jBDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 100, 80));

        jB7.setText("7");
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });
        jPanel1.add(jB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 100, 80));

        jB8.setText("8");
        jB8.setFocusPainted(false);
        jB8.setIconTextGap(0);
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });
        jPanel1.add(jB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 100, 80));

        jB9.setText("9");
        jB9.setFocusPainted(false);
        jB9.setIconTextGap(0);
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });
        jPanel1.add(jB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 100, 80));

        jBTimes.setText("×");
        jBTimes.setFocusPainted(false);
        jBTimes.setIconTextGap(0);
        jBTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTimesActionPerformed(evt);
            }
        });
        jPanel1.add(jBTimes, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 100, 80));

        jB4.setText("4");
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });
        jPanel1.add(jB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 100, 80));

        jB5.setText("5");
        jB5.setFocusPainted(false);
        jB5.setIconTextGap(0);
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });
        jPanel1.add(jB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 100, 80));

        jB6.setText("6");
        jB6.setFocusPainted(false);
        jB6.setIconTextGap(0);
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });
        jPanel1.add(jB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 100, 80));

        jBminus.setText("-");
        jBminus.setFocusPainted(false);
        jBminus.setIconTextGap(0);
        jBminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBminusActionPerformed(evt);
            }
        });
        jPanel1.add(jBminus, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 100, 80));

        jB1.setText("1");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
        jPanel1.add(jB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 100, 80));

        jB2.setText("2");
        jB2.setFocusPainted(false);
        jB2.setIconTextGap(0);
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });
        jPanel1.add(jB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 100, 80));

        jB3.setText("3");
        jB3.setFocusPainted(false);
        jB3.setIconTextGap(0);
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });
        jPanel1.add(jB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 100, 80));

        jBPlus.setText("+");
        jBPlus.setFocusPainted(false);
        jBPlus.setIconTextGap(0);
        jBPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPlusActionPerformed(evt);
            }
        });
        jPanel1.add(jBPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 100, 80));

        jB0.setText("0");
        jB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB0ActionPerformed(evt);
            }
        });
        jPanel1.add(jB0, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 200, 80));

        jBDot.setText(".");
        jBDot.setFocusPainted(false);
        jBDot.setIconTextGap(0);
        jBDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDotActionPerformed(evt);
            }
        });
        jPanel1.add(jBDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 100, 80));

        jBEqual.setText("=");
        jBEqual.setFocusPainted(false);
        jBEqual.setIconTextGap(0);
        jBEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEqualActionPerformed(evt);
            }
        });
        jPanel1.add(jBEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 100, 80));

        jBHappy.setText("(*￣︶￣)");
        jBHappy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHappyActionPerformed(evt);
            }
        });
        jPanel1.add(jBHappy, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 100, 80));

        jBCry.setText("o(╥﹏╥)o");
        jBCry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCryActionPerformed(evt);
            }
        });
        jPanel1.add(jBCry, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 100, 80));

        jBSad.setText("(⊙︿⊙)");
        jBSad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSadActionPerformed(evt);
            }
        });
        jPanel1.add(jBSad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 100, 80));

        jBHeart.setText("ღ( ´･ᴗ･` )");
        jBHeart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHeartActionPerformed(evt);
            }
        });
        jPanel1.add(jBHeart, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 100, 80));

        jBSr3.setText("(3√x)");
        jBSr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSr3ActionPerformed(evt);
            }
        });
        jPanel1.add(jBSr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 100, 80));

        jBSr2.setText("(2√x)");
        jBSr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSr2ActionPerformed(evt);
            }
        });
        jPanel1.add(jBSr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 100, 80));

        jBPowerX.setText("X^");
        jBPowerX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPowerXActionPerformed(evt);
            }
        });
        jPanel1.add(jBPowerX, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 100, 80));

        jBClosingBracket.setText(")");
        jBClosingBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClosingBracketActionPerformed(evt);
            }
        });
        jPanel1.add(jBClosingBracket, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 100, 80));

        jBOpeningBracket.setText("(");
        jBOpeningBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOpeningBracketActionPerformed(evt);
            }
        });
        jPanel1.add(jBOpeningBracket, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 100, 80));

        jBSquare.setText("X²");
        jBSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSquareActionPerformed(evt);
            }
        });
        jPanel1.add(jBSquare, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 100, 80));

        jBFile.setText("File");
        jBFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFileActionPerformed(evt);
            }
        });
        jPanel1.add(jBFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 60, 400));

        jTHistory.setColumns(20);
        jTHistory.setRows(5);
        jScrollPane3.setViewportView(jTHistory);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        jMenu1.setText("File");

        jMenuItem1.setText("File");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>                        

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        Operation.display(jText, db, "4");
    }                                   

    private void jB0ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        Operation.display(jText, db, "0");
    }                                   

    private void jBEqualActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String old = jText.getText();
        Operation.operation(db); 
        Operation.refresh(jText, db);
        db.addHistory(old + " :: " + jText.getText());
        jTHistory.setText(db.showHistory());
    }                                       

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        Operation.display(jText, db, "1");
    }                                   

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {                                    
       Operation.display(jText, db, "2");
    }                                   

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        Operation.display(jText, db, "3");
    }                                   

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        Operation.display(jText, db, "5");
    }                                   

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        Operation.display(jText, db, "6");
    }                                   

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        Operation.display(jText, db, "7");
    }                                   

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) {                                    
       Operation.display(jText, db, "8");
    }                                   

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        Operation.display(jText, db, "9");
    }                                   

    private void jBDotActionPerformed(java.awt.event.ActionEvent evt) {                                      
        Operation.display(jText, db, ".");
    }                                     

    private void jBPlusActionPerformed(java.awt.event.ActionEvent evt) {                                       
        Operation.display(jText, db, "+");
    }                                      

    private void jBminusActionPerformed(java.awt.event.ActionEvent evt) {                                        
        Operation.display(jText, db, "-");
    }                                       

    private void jBTimesActionPerformed(java.awt.event.ActionEvent evt) {                                        
        Operation.display(jText, db, "×");
    }                                       

    private void jBDivideActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Operation.display(jText, db, "÷");
    }                                        

    private void jBOpeningBracketActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        Operation.display(jText, db, "(");
    }                                                

    private void jBClosingBracketActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        Operation.display(jText, db, ")");
    }                                                

    private void jBAcActionPerformed(java.awt.event.ActionEvent evt) {                                     
        Operation.clean(jText, db);
    }                                    

    private void jBDelActionPerformed(java.awt.event.ActionEvent evt) {                                      
        Operation.del(jText, db);
    }                                     

    private void jBPercentageActionPerformed(java.awt.event.ActionEvent evt) {                                             
        Operation.display(jText, db, "%");
    }                                            

    private void jBPowerXActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Operation.display(jText, db, "^");
    }                                        

    private void jBSquareActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Operation.display(jText, db, "^2");
    }                                        

    private void jBSr3ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        Operation.display(jText, db, "(3√");
    }                                     

    private void jBCryActionPerformed(java.awt.event.ActionEvent evt) {                                      
        jTHistory.setText("Don't Cry. The hope never vanish!");
    }                                     

    private void jBSr2ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        Operation.display(jText, db, "(2√");
    }                                     

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
       jDFileChoose.setVisible(true);
    }                                          

    private void jFileChooserActionPerformed(java.awt.event.ActionEvent evt) {                                             
        try{
            
            if(jFileChooser.getSelectedFile() == null){
                jDFile.setVisible(false);
            }else{
                String path = jFileChooser.getSelectedFile().getPath();
                db.setAdd(path);
                jDFileChoose.setVisible(false);
                jTextArea1.setText(FileOperate.getFile(db.getAdd()));
                jDFile.setVisible(true);
                }
        }catch(Exception e){
            System.out.println("error: filecancel");
        }
    }                                            

    private void jBCalculateActionPerformed(java.awt.event.ActionEvent evt) {                                            
        jTMessage.setText("Operation succeed");
        jTextArea1.setText(FileOperate.operateFile(db.getAdd()));
    }                                           

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if(FileOperate.saveFile(db.getAdd(), jTextArea1.getText()) == true){
            jTMessage.setText("Save Succed!");
        }else{
            jTMessage.setText("Save Failure!");
        } 
    }                                      

    private void jBFileActionPerformed(java.awt.event.ActionEvent evt) {                                       
       jDFileChoose.setVisible(true);
    }                                      

    private void jBHappyActionPerformed(java.awt.event.ActionEvent evt) {                                        
        jTHistory.setText("Be Happy Everyday!");
    }                                       

    private void jBSadActionPerformed(java.awt.event.ActionEvent evt) {                                      
        jTHistory.setText("Big eyes!");
    }                                     

    private void jBHeartActionPerformed(java.awt.event.ActionEvent evt) {                                        
        jTHistory.setText("Love u!❥(^_-)");
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jB0;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBAc;
    private javax.swing.JButton jBCalculate;
    private javax.swing.JButton jBClosingBracket;
    private javax.swing.JButton jBCry;
    private javax.swing.JButton jBDel;
    private javax.swing.JButton jBDivide;
    private javax.swing.JButton jBDot;
    private javax.swing.JButton jBEqual;
    private javax.swing.JButton jBFile;
    private javax.swing.JButton jBHappy;
    private javax.swing.JButton jBHeart;
    private javax.swing.JButton jBOpeningBracket;
    private javax.swing.JButton jBPercentage;
    private javax.swing.JButton jBPlus;
    private javax.swing.JButton jBPowerX;
    private javax.swing.JButton jBSad;
    private javax.swing.JButton jBSave;
    private javax.swing.JButton jBSquare;
    private javax.swing.JButton jBSr2;
    private javax.swing.JButton jBSr3;
    private javax.swing.JButton jBTimes;
    private javax.swing.JButton jBminus;
    private javax.swing.JDialog jDFile;
    private javax.swing.JDialog jDFileChoose;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTHistory;
    private javax.swing.JTextField jTMessage;
    private javax.swing.JTextField jText;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}
